openapi: 3.0.0
info:
  description: "This is the short description of SELEXPED WEB endpoints."
  version: 1.0.0
  title: SELEXPED WEB LISTVIEW
  termsOfService: http://swagger.io/terms/
  contact:
    email: molnar.laszlo@selester.hu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:5000
tags:
  - name: api
    description: Checking service availability
  - name: api-docs
    description: Get this documentation from server
  - name: listview
    description: show data in dtat grid
  - name: localsystem
    description: gets and sets local system (usually SELEXPED) parameters.
paths:
  /api/heartbeat:
    get:
      tags:
        - api
      summary: Checking service availability
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/heartbeat'
  /api-docs:
    get:
      tags:
        - api-docs
      summary: Get this documentation
      responses:
        "200":
          description: OK

  /listview/data/:
    get:
      tags:
        - listview
      summary: Reading data from database (SYS_GRID)
      parameters:
        - in: header
          name: x-token
          description: valid token (see /localsystem/token get)
          required: true
          schema:
            type: string
        - in: header
          name: x-collection
          description: name of the collection to which the records belongs.
          required: true
          schema:
            type: string
        - in: header
          name: x-limit
          description: max amount of retrieved records.
          schema:
            type: integer
        - in: header
          name: x-filter
          description: Data filter
          schema:
            type: string
        - in: header
          name: x-sort
          description: sorts data after this segment
          schema:
            type: string
        - in: header
          name: x-language
          description: language of the query. (Some data may depend on the language setting.)
          schema:
            type: string
        - in: header
          name: x-pageno
          description: The page of the list.)
          schema:
            type: string
        - in: header
          name: x-rowsperpage
          description: Count of records on a page.)
          schema:
            type: string
      responses:
        '200':
          description: Data downloaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      $ref: '#/components/schemas/column'
                  data:
                    type: array
                    items:
                      type: object
    put:
      tags:
        - listview
      summary: upserting records in database (SYS_GRID)
      parameters:
        - in: header
          name: x-token
          description: valid token (see /localsystem/token get)
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                collection:
                  type: string
                  description: name of the collection to which the record belongs.
                data:
                  type: string
                  description: data of the record (json)
      responses:
        '200':
          description: Data saved successfully
        '400':
          description: Something went wrong
    delete:
      tags:
        - listview
      summary: removes records record from database (SYS_GRID)
      parameters:
        - in: header
          name: x-token
          description: valid token (see /localsystem/token get)
          required: true
          schema:
            type: string
        - in: header
          name: x-collection
          description: name of the collection to which the record belongs.
          required: true
          schema:
            type: string
        - in: header
          name: x-id
          description: id of record
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data deleted successfully
        '400':
          description: Something went wrong

  /localsystem/token:
    get:
      tags:
        - localsystem
      summary: Gets a token for the localsystem Client. Localsystem must be logged in and it must have a valid terminal id.
      parameters:
        - in: header
          name: localsystem_key
          description: Localsystem's current key
          required: true
          schema:
            type: string
        - in: header
          name: terminalid
          description: Localsystem's new key
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "403":
          description: Forbidden
  /localsystem/login:
    get:
      tags:
        - localsystem
      summary: Gets a token for a non localsystem Client. It logs into localsystem with login and password. This endpoint is with ip-whitelisting protected.
      parameters:
        - in: header
          name: localsystem_key
          description: Localsystem's current key
          required: true
          schema:
            type: string
        - in: header
          name: terminal
          description: name of the local terminal (e.g. 'INTERFACE')
          required: true
          schema:
            type: string
        - in: header
          name: login
          description: Localsystem's user login
          required: true
          schema:
            type: string
        - in: header
          name: password
          description: Localsystem's user password
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "403":
          description: Forbidden

components:
  schemas:
    heartbeat:
      type: object
      properties:
        product:
          type: string
        heartbeat:
          type: boolean
        version:
          type: string
        dbConnection:
          type: boolean
    column:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
